import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, it } from 'vitest';
import {
  type Contract,
  formatReport,
  type Report,
  runContract,
  summarise,
} from '../src/index.js';
import { engineContract, engineFixture } from './engine.contract.js';
import { goldenContract } from './store.contract.js';

/**
 * The contract run, and the artifact it produces.
 *
 * `report.md` is the point. Anyone who asks "what does this library actually
 * guarantee?" should be able to read one file and see a sentence per claim with a
 * pass or fail beside it, without opening the implementation. The unit suite
 * proves the same things and says less.
 *
 * There is one test that must pass, plus one per clause so a failure is
 * granular in CI. A single test collecting all failures is better for the report
 * and useless for bisecting, so it does both.
 */

const here = dirname(fileURLToPath(import.meta.url));
const REPORT_DIR = join(here, '..', 'coverage', 'contract');
const MARKDOWN = join(REPORT_DIR, 'report.md');
const JSON_PATH = join(REPORT_DIR, 'report.json');

const REPORTS: Report[] = [];

async function verify<I, O>(
  c: Contract<I, O>,
  makeInput: () => Promise<I>,
): Promise<Report> {
  const report = await runContract(c, await makeInput());
  REPORTS.push(report);

  expect(report.failed, formatReport(report)).toBe(0);
  return report;
}

it('the engine honours every guarantee it claims', async () => {
  await verify(engineContract, engineFixture);
});

it('every store honours the same contract', async () => {
  await verify(goldenContract, async () => undefined);
});

it('has at least one clause per guarantee the README claims', async () => {
  // A contract that silently loses clauses reports green on a smaller promise.
  expect(engineContract.clauses.length).toBeGreaterThanOrEqual(20);
  const ids = engineContract.clauses.map((c) => c.id);
  expect(new Set(ids).size).toBe(ids.length);
});

it('writes the QA report', async () => {
  // Runs last-ish, so `REPORTS` holds both contracts. Vitest does not guarantee
  // order, so if this runs first the report would be partial — hence the
  // explicit re-run below rather than trusting the accumulated array.
  const reports = [
    await runContract(engineContract, await engineFixture()),
    await runContract(goldenContract, await (async () => undefined)()),
  ];

  mkdirSync(REPORT_DIR, { recursive: true });
  writeFileSync(MARKDOWN, `${renderMarkdown(reports)}\n`, 'utf8');
  writeFileSync(
    JSON_PATH,
    `${JSON.stringify(
      {
        passed: reports.reduce((n, r) => n + r.passed, 0),
        failed: reports.reduce((n, r) => n + r.failed, 0),
        reports,
      },
      null,
      2,
    )}\n`,
    'utf8',
  );

  expect(reports.every((r) => r.failed === 0)).toBe(true);
}, 30_000);

function renderMarkdown(reports: readonly Report[]): string {
  const out: string[] = ['# Contract report', ''];
  out.push(
    'Generated by the Vitest contract run. Every line is a guarantee the library',
    'claims, checked against a real store. A ✗ means the claim is not currently true.',
    '',
  );
  out.push('```');
  out.push(summarise(reports));
  out.push('```');
  out.push('');

  for (const report of reports) {
    out.push(`## ${report.name}`);
    out.push('');
    out.push(`_${report.claim}_`);
    out.push('');
    out.push('| | guarantee | given | when | expected |');
    out.push('|---|---|---|---|---|');
    for (const r of report.results) {
      out.push(
        `| ${r.ok ? '✓' : '✗'} | \`${r.id}\` | ${r.given} | ${r.when} | ${r.expect} |`,
      );
    }
    out.push('');
  }
  return out.join('\n');
}
